jb4dc:
  system-caption: JB4DC-Builder
  system-title: JBuild4DC-应用构建系统
  warning-operation-code: jb4d82
  is-debug: true
  host:
    operation-system: Window
  file:
    root-path: production-files
  sso:
    server:
      name: JB4DC-SSO-WEB-SERVER
      context-path: /SSOSystem
      view:
        login: /Controller/LoginSSOView
        logout: https://127.0.0.1:19103/SSOSystem/Controller/LogoutSSOView
      excluded:
  builder:
    server:
      name: JB4DC-BUILDER-WEB-SERVER
      #address: http://localhost:9103
      context-path: /JB4DCBuilder

management:
  server:
  #port: #don't change it, then the port for actuator will be the same as server.port above
  endpoints:
    web:
      base-path: /actuator  #the default value for sring boot 2.x is /actuator, even you don't specify it, don't forget to include this in the URL
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring:
  profiles:
    active: dev
  application:
    name: JB4DC-BUILDER-WEB-SERVER
    inetutils:
      #客户端的IP
      #preferred-networks: 192.168.3.153
      #preferred-networks: 127.0.0.1
  liquibase:
    enabled: false
  thymeleaf:
    prefix: classpath:/static/HTML/
    suffix: .html
    enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 300MB

server:
  port: 9104
  servlet:
    session:
      timeout: 7200
    context-path: /JB4DCBuilder

logging:
  level:
    com:
      jb4dc:
        builder:
          dao: TRACE
        devmock:
          dao: TRACE
        sso:
          client: TRACE

feign:
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 12000
        retryer: feign.Retryer.Default

camunda:
  bpm:
    database:
      schema-update: false
    application:
      delete-upon-undeploy: false
      scan-for-process-definitions: false
      deploy-changed-only: true
      resume-previous-versions: true
      resume-previous-by: a value
    job-execution:
      enabled: true
    metrics:
      enabled: false
      db-reporter-activate: false
    auto-deployment-enabled: false